name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

env:
  RUST_BACKTRACE: "1"

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PUSH_DOCKER_CACHE: ${{ secrets.REGISTRY_PASS != '' && '1' || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker registry
        if: ${{ env.PUSH_DOCKER_CACHE == '1' }}
        run: echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Pull dependencies image cache
        run: docker pull marwes/try_gluon:dependencies || true

      - name: Pull builder image cache on master
        if: ${{ github.base_ref == 'master' || github.ref_name == 'master' }}
        run: docker pull marwes/try_gluon:builder || true

      - name: Run CI script
        run: ./scripts/ci.sh

      - name: List Docker images
        if: always()
        run: docker images
